config/routes.rb
Rails.application.routes.draw do
  root to: "questions#index"

  namespace :admin do
    resources :users
    resources :questions, only: [:index, :destroy]
  end

  resources :questions do
    collection do
      get :solved
      get :unsolved
    end

    member do
      post :solve
    end
    resources :answers, only: [:create]
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :user
    scope :recent, -> { order(created_at: :desc)}
    has_many :answers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :questions, dependent: :destroy
    has_one_attached :image, dependent: :destroy
    has_many :answers, dependent: :destroy
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy!
    redirect_to admin_questions_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
        redirect_to admin_user_path(@user)
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_user_path
  end

  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to admin_user_path(@user)
    else
        render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :image, :admin, :password, :password_confirmation)
  end

  def require_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    question = Question.find(params[:question_id])
    @answer = question.answers.build(answer_params)
    @answer.user_id = current_user.id
    if @answer.save
      flash[:success] = "コメントしました"
    else
      flash[:success] = "コメントできませんでした"
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @q = current_user.questions.ransack(params[:q])
    @questions = @q.result(distinct: true).page(params[:page]).per(5)
  end

  def solved
    @q = Question.where(solved: true).ransack(params[:q])
    @questions = @q.result(distinct: true).page(params[:page]).per(5)
  end

  def unsolved
    @q = Question.where(solved: false).ransack(params[:q])
    @questions = @q.result(distinct: true).page(params[:page]).per(5)
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def edit
    @question = current_user.questions.find(params[:id])
  end

  def update
    @question = current_user.questions.find(params[:id])
    if @question.update(question_params)
      redirect_to questions_url
    else
      render :edit
    end
  end

  def destroy
    @question = current_user.questions.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  
  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    if @question.save
      QuestionMailer.creation_email(@question).deliver_now
      redirect_to questions_url
    else
      flash.now[:danger] = "失敗しました"
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :solved, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :newf
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/views/admin/questions/index.html.erb
<h1>Admin::Questions#index</h1>
<p>Find me in app/views/admin/questions/index.html.erb</p>

app/views/admin/users/_form.html.erb
<div class = "session-new">
  <%= form_with model: [:admin, user] do |f| %>
    <%= f.label :nickname, "ニックネーム"  %><br>
    <%= f.text_field :nickname %><br>
  
    <%= f.label :email, "メールアドレス"  %><br>
    <%= f.text_field :email %><br>
  
    <%= f.label :image, "プロフィール画像"  %><br>
    <%= f.file_field :image, class: 'form-control'%><br>
  
    <%= f.label :admin  %><br>
    <%= f.check_box :admin %><br>
  
    <%= f.label :password, "パスワード"  %><br>
    <%= f.password_field :password %><br>
  
    <%= f.label :password_confirmation, "パスワード(確認)"  %><br>
    <%= f.password_field :password_confirmation %><br>
  
    <%= f.submit "登録", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/admin/users/edit.html.erb
<%= render partial: "form", locals: { user: @user } %>

app/views/admin/users/index.html.erb
<div class="user-container">
  <% @users.each do |user| %>
  <div class="image">
  <%= image_tag user.image, class: "rounded-circle", size: "120x120" if user.image.attached? %>
  </div>
  <div class="nickname">
  <%= link_to user.nickname, [:admin, user] %>
  </div>
    
  <div class="right-container">
    <%= link_to "編集", edit_admin_user_path(user), class: "btn btn-primary mr-3" %>
    <%= link_to "削除", [:admin, user], method: :delete, class: "btn btn-primary mr-3" %>
  </div>
  <% end %>
</div>

app/views/admin/users/new.html.erb
<%= render partial: "form", locals: { user: @user } %>

app/views/admin/users/question.html.erb
<h1>管理者画面：質問一覧</h1>
  <div class="solved">
    <table border="1">
      <tr>
      <th><%= link_to "全て", questions_path, class: "btn btn-primary mr-3" %></th>
      <th><%= link_to "解決済質問", solved_questions_path, class: "btn btn-primary mr-3" %></th>
      <th><%= link_to "未解決質問", unsolved_questions_path, class: "btn btn-primary mr-3" %></th>
      </tr>
    </table>
  </div>

<div class="search">
  <%= search_form_for @q do |f| %>
    <%= f.search_field :body_cont, placeholder:"検索ワード" %>
    <%= f.submit "検索" %>
  <% end %>
  </div>
  
    <% @questions.each do |question| %>
      <div class="question-container">
          <div class="image">
            <%= image_tag question.user.image, class: "rounded-circle", size: "120x120" if question.user.image.attached? %>
            <p><%= question.user.nickname %></p>
          </div>
          <div class="question-title">
            <%= link_to question.title, question %>
            <% if question.solved %>
            <%= ":解決済み" %>
            <% else %>
            <%= ":未解決"%>
            <% end %>
          </div>
      </div>
    <% end %>

  
  <div class="page">
  <%= paginate @questions %>
  </div>
</div>

app/views/admin/users/show.html.erb
<h1>Admin::Users#show</h1>
<%= @user.id %>
<%= image_tag @user.image if @user.image.attached? %>
<%= @user.nickname %>
<%= @user.email %>
<%= @user.admin? ? "あり" : "なし" %>
<%= @user.created_at %>
<%= @user.updated_at %>
<%= link_to "編集", edit_admin_user_path, class: "btn btn-primary mr-3" %>
<%= link_to "削除", [:admin, @user], method: :delete, class: "btn btn-primary mr-3" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learning</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Learning</h1>
      <div class="header-list">
        <ul>
        <% if current_user %>
        <li><%= link_to "新規投稿", new_question_path %></li>
        <li><%= link_to "質問一覧", questions_path%></li>
          <% if current_user.admin? %>
            <li><%= link_to "管理者：ユーザー一覧", admin_users_path%></li>
            <li><%= link_to "管理者：質問一覧", admin_users_question_path%></li>
            <li><%= link_to "管理者：新規ユーザー作成", new_admin_user_path%></li>
          <% end %>
        <li><%= link_to "ログアウト", logout_path, method: :delete%></li>
        <% else %>
        <li><%= link_to "ログイン", login_path %></li>
        <% end %>
        </ul>
      </div>
    </header>
    <main>
        <%= yield %>
    </main>
  </body>
</html>

app/views/questions/_form.html.erb
<div class="post-container">
  <p class="title">投稿フォーム</p>
  <%= form_with model: question do |f| %>
    <%= f.label :solved, "解決済みにする"  %>
    <%= f.check_box :solved, id:"solved_questions" %>
    <br>
    <br>
    <%= f.label :title, "質問タイトル"  %>
    <br>
    <%= f.text_field :title, id: "question_title" %>
    <br>
    <%= f.label :body, "質問内容"  %>
    <br>
    <%= f.text_field :body, id: "question_body" %>
    <br>
    <%= f.submit "投稿", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/questions/edit.html.erb
<h1>Questions#edit</h1>

<%= render partial: "form", locals: { question: @question } %>

app/views/questions/index.html.erb
<div class="index">
  <div class="solved">
    <table border="1">
      <tr>
      <th><%= link_to "全て", questions_path, class: "btn btn-primary mr-3" %></th>
      <th><%= link_to "解決済質問", solved_questions_path, class: "btn btn-primary mr-3" %></th>
      <th><%= link_to "未解決質問", unsolved_questions_path, class: "btn btn-primary mr-3" %></th>
      </tr>
    </table>
  </div>

  <div class="search">
  <%= search_form_for @q do |f| %>
    <%= f.search_field :body_cont, placeholder:"検索ワード" %>
    <%= f.submit "検索" %>
  <% end %>
  </div>
  
  
    <% @questions.each do |question| %>
      <div class="question-container">
          <div class="image">
            <%= image_tag question.user.image, class: "rounded-circle", size: "120x120" if question.user.image.attached? %>
            <p><%= question.user.nickname %></p>
          </div>
          <div class="question-title">
            <%= link_to question.title, question %>
            <% if  question.solved %>
            <%= ":解決済み" %>
            <% else %>
            <%= ":未解決"%>
            <% end %>
          </div>
      </div>
    <% end %>

  
  <div class="page">
  <%= paginate @questions %>
  </div>
</div>

app/views/questions/new.html.erb
<%= render partial: "form", locals: { question: @question } %>

app/views/questions/show.html.erb
<div class="question-detail">
  <div class="question-user">
    <%= image_tag @question.user.image, class: "rounded-circle", size: "120x120" if @question.user.image.attached? %>
    <p><%= @question.user.nickname %></p>
  </div>

  <div class="question-content">
    <%= @question.title %><br>
    <%= @question.body %>
  </div>

  <div class="edit">
    <% if  current_user.id == @question.user_id %>
      <%= link_to "編集", edit_question_path(@question), class: "btn btn-primary mr-3" %><br>
      <%= link_to "削除", @question, method: :delete, class: "btn btn-primary mr-3" %>
    <% end %>
  </div>
</div>

<div class="comment-container">
  <div class="comment">
  <%= form_with(model: [@question, @answer], local: true) do |f| %>
  <%= f.text_area :content ,size: "80x8"%><br>
  <%= button_tag type: "submit" do %>
      <i class="far fa-comments"></i> 回答する
  <% end %>
  <% end %>
</div>


<% @answers.each do |c|%>
  <div class="question-detail">
    <div class="question-user">
      <%= image_tag @question.user.image, class: "rounded-circle", size: "120x120" if @question.user.image.attached? %>
      <p><%= @question.user.nickname %></p>
    </div>
  
    <div class="question-content">
      <%= c.content%>
    </div>
  </div>
<% end %>

app/views/questions/solved.html.erb
<div class="index">
  <div class="solved">
      <table border="1">
        <tr>
        <th><%= link_to "全て", questions_path, class: "btn btn-primary mr-3" %></th>
        <th><%= link_to "解決済質問", solved_questions_path, class: "btn btn-primary mr-3" %></th>
        <th><%= link_to "未解決質問", unsolved_questions_path, class: "btn btn-primary mr-3" %></th>
        </tr>
      </table>
  </div>
  
  <div class="search">
  <%= search_form_for @q do |f| %>
    <%= f.search_field :body_cont , placeholder:"検索ワード" %>
    <%= f.submit  "検索" %>
  <% end %>
  </div>
  
  <% @questions.each do |question| %>
    <div class="question-container">
        <div class="image">
            <%= image_tag question.user.image, class: "rounded-circle", size: "120x120" if question.user.image.attached? %>
            <p><%= question.user.nickname %></p>
        </div>
        <div class="question-title">
        <%= link_to question.title, question %>
        </div>
      </div>
  <% end %>
  
  <div class="page">
  <%= paginate @questions %>
  </div>

</div>






app/views/questions/unsolved.html.erb
<div class="index">
  <div class="solved">
      <table border="1">
        <tr>
        <th><%= link_to "全て", questions_path, class: "btn btn-primary mr-3" %></th>
        <th><%= link_to "解決済質問", solved_questions_path, class: "btn btn-primary mr-3" %></th>
        <th><%= link_to "未解決質問", unsolved_questions_path, class: "btn btn-primary mr-3" %></th>
        </tr>
      </table>
  </div>
  
  <div class="search">
  <%= search_form_for @q do |f| %>
    <%= f.search_field :body_cont , placeholder:"検索ワード" %>
    <%= f.submit  "検索" %>
  <% end %>
  </div>
  
  <% @questions.each do |question| %>
    <div class="question-container">
        <div class="image">
            <%= image_tag question.user.image, class: "rounded-circle", size: "120x120" if question.user.image.attached? %>
            <p><%= question.user.nickname %></p>
        </div>
        <div class="question-title">
        <%= link_to question.title, question %>
        </div>
      </div>
  <% end %>

  <div class="page">
    <%= paginate @questions %>
  </div>
</div>